name: 'Cached Dependencies'
description: 'Get the dependencies and cache them; pnpm.'
runs:
  using: 'composite'
  steps:
    - name: Get pnpm store
      shell: bash
      run: echo "STORE_PATH=$(pnpm store path --silent)" >> "$GITHUB_ENV"
    # Cache the pnpm store, then install to recreate node_modules on each runner.
    - name: Cache pnpm
      id: cache-pnpm
      uses: actions/cache@v4
      with:
        path: ${{ env.STORE_PATH }}
        key: pnpm-${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
    - name: Install dependencies
      shell: bash
      run: pnpm install --frozen-lockfile
