name: Print Workflow
on: workflow_dispatch
jobs:
  print-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hi
        run: echo 'Hi'
      - name: Print Hello
        run: echo 'Hello'
      - name: Print Bye
        run: echo 'Bye'
