name: Secrets Management
on: [workflow_dispatch, push]
# HERE
env:
  GROQ_MODEL: openai/gpt-oss-120b
jobs:
  test:
    # HERE
    environment: prod
    env:
      GROQ_MODEL: openai/gpt-oss-20b
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 24
      - name: Setup pnpm
        run: |
          corepack enable
          corepack prepare pnpm@11 --activate
      - name: Get pnpm store
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> "$GITHUB_ENV"
      - name: Cache pnpm
        uses: actions/cache@v4
        with:
          path: ${{ env.STORE_PATH }}
          key: pnpm-${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Run
        run: pnpm run build
      - name: Deploy
        run: |
          echo "Deploying rag app..."
          echo "${{ env.GROQ_MODEL }}"
          echo "$GROQ_MODEL"
          pnpm run start &
          pnpm dlx wait-on http://localhost:$PORT
          echo "RAG app is running"
